version: '3'
services:
    http:
        image: "nginx:1.15"
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./dist:/var/static:ro
        depends_on:
            - "app"
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/home/app
        depends_on:
            - "db"
    db:
        image: "postgres:10.4"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
